name: thatguyyoulove/angular.js
author:
  name: Colton McCormack
  email: thatguyyoulove@gmail.com
  url: 'http://thatguyyoulove.com'
copyright: 2015 Colton McCormack
description: HTML enhanced for web apps
